# Enable C++ support
language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx
compiler:
  - gcc
  - clang
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install -qq g++-4.8;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install gcc48;
    fi
  - if [ "$CXX" = "g++" ]; then
        export CXX="g++-5" CC="gcc-5";
    fi
addons:
  apt:
    packages:
    - gcc-5
    - g++-5
    - clang
script:
  - mkdir build
  - cd build
  - cmake .. && make
